const std = @import("std");
const zlinter = @import("zlinter");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const i18n_generator = b.addExecutable(.{
        .name = "i18n-generator",
        .root_module = b.createModule(.{
            .root_source_file = b.path("tools/i18n_gen.zig"),
            .target = b.graph.host,
            .optimize = .ReleaseSafe,
        }),
    });
    const render_i18n = b.addRunArtifact(i18n_generator);
    render_i18n.addFileArg(b.path("src/web/index.html.in"));
    render_i18n.addFileArg(b.path("src/web/locales/pl.json"));
    render_i18n.addFileArg(b.path("src/web/locales/en.json"));
    const i18n_source = render_i18n.addOutputFileArg("i18n.zig");
    // The generator draws the weather icons from this file into /icons.svg and
    // /favicon.svg.
    render_i18n.addFileArg(b.path("src/web/weather_icons.txt"));
    // The page links each asset by a hash of its content, so the generator
    // must see the assets as inputs: as file arguments the step re-runs when
    // one changes, and a plain path string would leave the hash stale.
    for ([_][]const u8{ "98.css", "app.css", "app.js", "alpine.js", "qrcode.js" }) |asset| {
        render_i18n.addFileArg(b.path(b.fmt("src/web/{s}", .{asset})));
    }
    const i18n_module = b.createModule(.{
        .root_source_file = i18n_source,
        .target = target,
        .optimize = optimize,
    });

    // The Antistorm city table is a data file, generated by this tool and
    // committed: the module embeds it and decodes it while compiling, so the
    // build itself never reaches the network. Re-run this step when Antistorm
    // adds or reorders a city, because the position of an entry in the file is
    // the id its webservice expects.
    const cities_generator = b.addExecutable(.{
        .name = "antistorm-gen",
        .root_module = b.createModule(.{
            .root_source_file = b.path("tools/antistorm_gen.zig"),
            .target = b.graph.host,
            .optimize = .ReleaseSafe,
        }),
    });
    const render_cities = b.addRunArtifact(cities_generator);
    render_cities.addArg("src/antistorm/cities.json");
    const cities_step = b.step("cities", "Regenerate src/antistorm/cities.json from Antistorm");
    cities_step.dependOn(&render_cities.step);

    const exe = serverExe(b, target, optimize, i18n_source);
    b.installArtifact(exe);

    const run_step = b.step("run", "Run the server");
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    run_step.dependOn(&run_cmd.step);

    // A deployment builds this profile, so a local measurement of the server's
    // memory only means something when it runs one too: the debug build keeps
    // several megabytes of its own code and data resident, which no amount of
    // work in the server can give back.
    const release_exe = serverExe(b, target, .ReleaseSafe, i18n_source);
    const run_release_step = b.step("run-release", "Run the server built with the release profile");
    const run_release_cmd = b.addRunArtifact(release_exe);
    if (b.args) |args| run_release_cmd.addArgs(args);
    run_release_step.dependOn(&run_release_cmd.step);

    const tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const test_sqlite = b.dependency("sqlite", .{
        .target = target,
        .optimize = optimize,
    });
    const test_zeit = b.dependency("zeit", .{
        .target = target,
        .optimize = optimize,
    });
    tests.root_module.addImport("i18n", i18n_module);
    tests.root_module.addImport("sqlite", test_sqlite.module("sqlite"));
    tests.root_module.addImport("zeit", test_zeit.module("zeit"));
    if (target.result.os.tag == .macos) tests.root_module.linkSystemLibrary("proc", .{});
    const run_tests = b.addRunArtifact(tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_tests.step);

    const i18n_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("tools/i18n_gen.zig"),
            .target = b.graph.host,
            .optimize = optimize,
        }),
    });
    const run_i18n_tests = b.addRunArtifact(i18n_tests);
    test_step.dependOn(&run_i18n_tests.step);

    // The linter walks only the sources this repository owns: `zig-pkg/` holds
    // vendored dependencies and `src/web/` holds browser assets, neither of
    // which this project is free to rename or rewrite.
    const lint_step = b.step("lint", "Lint source code");
    lint_step.dependOn(step: {
        var builder = zlinter.builder(b, .{});
        builder.addPaths(.{
            .include = &.{ b.path("src"), b.path("tools"), b.path("build.zig") },
        });
        builder.addRule(.{ .builtin = .field_naming }, .{
            // The rule's own defaults (x, y, z, i, b, it, ip, c, io), plus:
            // `id`, `db`, and the IMGW/Antistorm wire fields `m`/`s`/`to` (see
            // src/imgw/records.zig, src/imgw/warning_fields.zig and
            // src/antistorm/client.zig) are clear in their one-line context;
            // the wire fields must additionally match the source's JSON keys
            // exactly, since std.json derives them from the field name (see
            // AGENTS.md). build.zig cannot reach the library's internal
            // default list, so it is repeated here.
            // The two long names are IMGW's own field and its English mapping
            // (src/imgw/hydro.zig and src/weather/store.zig); shortening either
            // would break the wire-name match or make the column name unclear.
            .struct_field_exclude_len = &.{
                "x",  "y",  "z", "i", "b",  "it",                               "ip",                                "c", "io",
                "id", "db", "m", "s", "to", "zjawisko_zarastania_data_pomiaru", "overgrowth_phenomenon_observed_at",
            },
        });
        builder.addRule(.{ .builtin = .field_ordering }, .{});
        builder.addRule(.{ .builtin = .declaration_naming }, .{
            // The rule's own defaults (x, y, z, i, b, it, ip, c, io), plus:
            // `n` (a byte count), `at` (an index) and `fd` (a POSIX file
            // descriptor) are standard short names; `id` names an entity id
            // throughout src/antistorm/client.zig. build.zig cannot reach the
            // library's internal default list, so it is repeated here.
            .decl_name_exclude_len = &.{ "x", "y", "z", "i", "b", "it", "ip", "c", "io", "n", "at", "fd", "id" },
        });
        builder.addRule(.{ .builtin = .function_naming }, .{});
        builder.addRule(.{ .builtin = .file_naming }, .{});
        builder.addRule(.{ .builtin = .switch_case_ordering }, .{});
        builder.addRule(.{ .builtin = .no_unused }, .{});
        builder.addRule(.{ .builtin = .no_deprecated }, .{});
        builder.addRule(.{ .builtin = .no_orelse_unreachable }, .{});
        builder.addRule(.{ .builtin = .no_swallow_error }, .{});
        builder.addRule(.{ .builtin = .no_undefined }, .{});
        break :step builder.build();
    });

    const antistorm_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("tools/antistorm_gen.zig"),
            .target = b.graph.host,
            .optimize = optimize,
        }),
    });
    const run_antistorm_tests = b.addRunArtifact(antistorm_tests);
    test_step.dependOn(&run_antistorm_tests.step);
}

/// The server, wired for one optimization profile. The `run` and `run-release`
/// steps differ only in the profile they build, so the imports and the platform
/// libraries live here once.
fn serverExe(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    i18n_source: std.Build.LazyPath,
) *std.Build.Step.Compile {
    const exe = b.addExecutable(.{
        .name = "szklana-pogoda",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const i18n_module = b.createModule(.{
        .root_source_file = i18n_source,
        .target = target,
        .optimize = optimize,
    });
    const sqlite = b.dependency("sqlite", .{
        .target = target,
        .optimize = optimize,
    });
    const zeit = b.dependency("zeit", .{
        .target = target,
        .optimize = optimize,
    });
    exe.root_module.addImport("i18n", i18n_module);
    exe.root_module.addImport("sqlite", sqlite.module("sqlite"));
    exe.root_module.addImport("zeit", zeit.module("zeit"));
    if (target.result.os.tag == .macos) exe.root_module.linkSystemLibrary("proc", .{});
    return exe;
}
