const std = @import("std");

const max_file_bytes = 1024 * 1024;

/// A template key of the form `version:app.js` stands for the content hash of
/// the asset that file names, so a page can link `/app.js?v=<hash>` and the URL
/// changes exactly when the asset does.
const version_prefix = "version:";

/// The content hash of one browser asset, keyed by its file name.
const AssetVersion = struct {
    name: []const u8,
    hash: u64,
};

/// Arguments: template, pl locale, en locale, output file, the weather icon
/// source, then every browser asset the template links. Each is a build input,
/// so editing one re-renders the page with its new hash. The icon source is
/// rendered here into `/icons.svg` and `/favicon.svg`, which are hashed and
/// linked like any asset.
pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len < 6) return error.InvalidArguments;

    const allocator = init.gpa;
    const cwd = std.Io.Dir.cwd();
    const template = try cwd.readFileAlloc(init.io, args[1], allocator, .limited(max_file_bytes));
    defer allocator.free(template);
    const pl_locale = try cwd.readFileAlloc(init.io, args[2], allocator, .limited(max_file_bytes));
    defer allocator.free(pl_locale);
    const en_locale = try cwd.readFileAlloc(init.io, args[3], allocator, .limited(max_file_bytes));
    defer allocator.free(en_locale);

    const icon_source = try cwd.readFileAlloc(init.io, args[5], allocator, .limited(max_file_bytes));
    defer allocator.free(icon_source);
    const icons = try renderIcons(allocator, icon_source);
    defer icons.deinit(allocator);

    var versions: std.ArrayList(AssetVersion) = .empty;
    defer versions.deinit(allocator);
    for (args[6..]) |path| {
        const asset = try cwd.readFileAlloc(init.io, path, allocator, .limited(max_file_bytes));
        defer allocator.free(asset);
        try versions.append(allocator, .{ .name = std.Io.Dir.path.basename(path), .hash = std.hash.Wyhash.hash(0, asset) });
    }
    try versions.append(allocator, .{ .name = "icons.svg", .hash = std.hash.Wyhash.hash(0, icons.sprite) });
    try versions.append(allocator, .{ .name = "favicon.svg", .hash = std.hash.Wyhash.hash(0, icons.favicon) });

    const pl_html = try render(allocator, template, pl_locale, versions.items);
    defer allocator.free(pl_html);
    const en_html = try render(allocator, template, en_locale, versions.items);
    defer allocator.free(en_html);

    var generated: std.Io.Writer.Allocating = .init(allocator);
    defer generated.deinit();
    try generated.writer.print(
        "// Generated by tools/i18n_gen.zig; do not edit.\n" ++
            "pub const pl_html = \"{f}\";\n" ++
            "pub const en_html = \"{f}\";\n" ++
            "pub const icons_svg = \"{f}\";\n" ++
            "pub const favicon_svg = \"{f}\";\n" ++
            "pub const versions = struct {{\n",
        .{
            std.zig.fmtString(pl_html),
            std.zig.fmtString(en_html),
            std.zig.fmtString(icons.sprite),
            std.zig.fmtString(icons.favicon),
        },
    );
    for (versions.items) |version| {
        try generated.writer.print(
            "    pub const {f} = \"{x:0>16}\";\n",
            .{ std.zig.fmtId(version.name), version.hash },
        );
    }
    try generated.writer.writeAll("};\n");

    try cwd.writeFile(init.io, .{ .sub_path = args[4], .data = generated.written() });
}

fn render(
    allocator: std.mem.Allocator,
    template: []const u8,
    locale_json: []const u8,
    versions: []const AssetVersion,
) ![]u8 {
    var parsed = try std.json.parseFromSlice(std.json.Value, allocator, locale_json, .{});
    defer parsed.deinit();

    const translations = switch (parsed.value) {
        .object => |object| object,
        else => return error.LocaleMustBeObject,
    };

    var output: std.ArrayList(u8) = .empty;
    errdefer output.deinit(allocator);

    var position: usize = 0;
    while (std.mem.findPos(u8, template, position, "{{")) |open| {
        try output.appendSlice(allocator, template[position..open]);
        const key_start = open + 2;
        const close_relative = std.mem.find(u8, template[key_start..], "}}") orelse {
            return error.UnclosedPlaceholder;
        };
        const key_end = key_start + close_relative;
        const key = template[key_start..key_end];
        if (key.len == 0) {
            return error.EmptyPlaceholder;
        }

        if (std.mem.startsWith(u8, key, version_prefix)) {
            const hash = findVersion(versions, key[version_prefix.len..]) orelse return error.UnknownAsset;
            try output.print(allocator, "{x:0>16}", .{hash});
            position = key_end + 2;
            continue;
        }

        const value = translations.get(key) orelse return error.MissingTranslation;
        const text = switch (value) {
            .string => |string| string,
            else => return error.TranslationMustBeString,
        };
        try appendHtmlEscaped(&output, allocator, text);
        position = key_end + 2;
    }
    try output.appendSlice(allocator, template[position..]);

    return output.toOwnedSlice(allocator);
}

const icon_size = 16;

/// The rendered icon files: one sprite with a `<symbol>` per icon, and the
/// favicon as a stand-alone SVG.
const IconFiles = struct {
    sprite: []u8,
    favicon: []u8,

    fn deinit(self: IconFiles, allocator: std.mem.Allocator) void {
        allocator.free(self.sprite);
        allocator.free(self.favicon);
    }
};

const Icon = struct {
    name: []const u8,
    rows: [icon_size][]const u8 = @splat(""),
    row_count: usize = 0,
};

/// Parses the icon source (see `src/web/weather_icons.txt`) and renders it.
/// Every mistake in the file is an error naming the kind of fault, so a broken
/// icon fails the build instead of shipping as a blank image.
fn renderIcons(allocator: std.mem.Allocator, source: []const u8) !IconFiles {
    var palette: [128]?[]const u8 = @splat(null);
    var icons: std.ArrayList(Icon) = .empty;
    defer icons.deinit(allocator);
    var favicon_name: ?[]const u8 = null;

    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |raw| {
        const line = std.mem.trim(u8, raw, " \t\r");
        if (line.len == 0 or line[0] == '#') continue;

        if (std.mem.startsWith(u8, line, "palette ")) {
            var fields = std.mem.tokenizeScalar(u8, line["palette ".len..], ' ');
            const letter = fields.next() orelse return error.BadPaletteLine;
            const color = fields.next() orelse return error.BadPaletteLine;
            if (letter.len != 1 or letter[0] >= palette.len or letter[0] == '.') return error.BadPaletteLine;
            if (!isHexColor(color)) return error.BadPaletteColor;
            palette[letter[0]] = color;
        } else if (std.mem.startsWith(u8, line, "favicon ")) {
            favicon_name = std.mem.trim(u8, line["favicon ".len..], " ");
        } else if (std.mem.startsWith(u8, line, "icon ")) {
            if (icons.items.len > 0 and icons.items[icons.items.len - 1].row_count != icon_size) return error.IncompleteIcon;
            const name = std.mem.trim(u8, line["icon ".len..], " ");
            if (name.len == 0 or findIcon(icons.items, name) != null) return error.BadIconName;
            try icons.append(allocator, .{ .name = name });
        } else {
            if (icons.items.len == 0) return error.RowOutsideIcon;
            const icon = &icons.items[icons.items.len - 1];
            if (icon.row_count == icon_size) return error.TooManyRows;
            if (line.len != icon_size) return error.BadRowWidth;
            for (line) |letter| {
                if (letter != '.' and (letter >= palette.len or palette[letter] == null)) return error.UnknownPaletteLetter;
            }
            icon.rows[icon.row_count] = line;
            icon.row_count += 1;
        }
    }

    if (icons.items.len == 0) return error.NoIcons;
    if (icons.items[icons.items.len - 1].row_count != icon_size) return error.IncompleteIcon;
    const favicon_icon = findIcon(icons.items, favicon_name orelse return error.NoFavicon) orelse return error.UnknownFavicon;

    var sprite: std.ArrayList(u8) = .empty;
    errdefer sprite.deinit(allocator);
    try sprite.appendSlice(allocator, "<svg xmlns=\"http://www.w3.org/2000/svg\">\n");
    for (icons.items) |icon| {
        try sprite.print(allocator, "<symbol id=\"{s}\" viewBox=\"0 0 {d} {d}\" shape-rendering=\"crispEdges\">", .{ icon.name, icon_size, icon_size });
        try appendRects(&sprite, allocator, icon, &palette);
        try sprite.appendSlice(allocator, "</symbol>\n");
    }
    try sprite.appendSlice(allocator, "</svg>\n");

    var favicon: std.ArrayList(u8) = .empty;
    errdefer favicon.deinit(allocator);
    try favicon.print(
        allocator,
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {d} {d}\" shape-rendering=\"crispEdges\">",
        .{ icon_size, icon_size },
    );
    try appendRects(&favicon, allocator, favicon_icon.*, &palette);
    try favicon.appendSlice(allocator, "</svg>\n");

    return .{ .sprite = try sprite.toOwnedSlice(allocator), .favicon = try favicon.toOwnedSlice(allocator) };
}

fn findIcon(icons: []Icon, name: []const u8) ?*Icon {
    for (icons) |*icon| {
        if (std.mem.eql(u8, icon.name, name)) return icon;
    }
    return null;
}

fn isHexColor(text: []const u8) bool {
    if (text.len != 7 or text[0] != '#') return false;
    for (text[1..]) |digit| {
        if (!std.ascii.isHex(digit)) return false;
    }
    return true;
}

/// One `<rect>` per horizontal run of a single colour, which is far fewer
/// elements than one per pixel.
fn appendRects(output: *std.ArrayList(u8), allocator: std.mem.Allocator, icon: Icon, palette: *const [128]?[]const u8) !void {
    for (icon.rows[0..icon.row_count], 0..) |row, y| {
        var x: usize = 0;
        while (x < row.len) {
            const letter = row[x];
            var end = x + 1;
            while (end < row.len and row[end] == letter) end += 1;
            if (letter != '.') {
                try output.print(
                    allocator,
                    "<rect x=\"{d}\" y=\"{d}\" width=\"{d}\" height=\"1\" fill=\"{s}\"/>",
                    .{ x, y, end - x, palette[letter].? },
                );
            }
            x = end;
        }
    }
}

fn findVersion(versions: []const AssetVersion, name: []const u8) ?u64 {
    for (versions) |version| {
        if (std.mem.eql(u8, version.name, name)) return version.hash;
    }
    return null;
}

fn appendHtmlEscaped(output: *std.ArrayList(u8), allocator: std.mem.Allocator, text: []const u8) !void {
    for (text) |byte| switch (byte) {
        '&' => try output.appendSlice(allocator, "&amp;"),
        '<' => try output.appendSlice(allocator, "&lt;"),
        '>' => try output.appendSlice(allocator, "&gt;"),
        '\"' => try output.appendSlice(allocator, "&quot;"),
        '\'' => try output.appendSlice(allocator, "&#39;"),
        else => try output.append(allocator, byte),
    };
}

test "render substitutes translations and escapes HTML" {
    const template = "<p title=\"{{title}}\">{{message}}</p>";
    const locale =
        \\{
        \\  "title": "A & B",
        \\  "message": "Use <tags> safely"
        \\}
    ;

    const rendered = try render(std.testing.allocator, template, locale, &.{});
    defer std.testing.allocator.free(rendered);

    try std.testing.expectEqualStrings("<p title=\"A &amp; B\">Use &lt;tags&gt; safely</p>", rendered);
}

test "render rejects a missing translation" {
    try std.testing.expectError(
        error.MissingTranslation,
        render(std.testing.allocator, "{{missing}}", "{}", &.{}),
    );
}

test "render substitutes the content hash of a named asset" {
    const versions = [_]AssetVersion{
        .{ .name = "app.js", .hash = 0xabc },
        .{ .name = "app.css", .hash = 0x1 },
    };
    const rendered = try render(
        std.testing.allocator,
        "<script src=\"/app.js?v={{version:app.js}}\"></script><link href=\"/app.css?v={{version:app.css}}\">",
        "{}",
        &versions,
    );
    defer std.testing.allocator.free(rendered);

    try std.testing.expectEqualStrings(
        "<script src=\"/app.js?v=0000000000000abc\"></script><link href=\"/app.css?v=0000000000000001\">",
        rendered,
    );
}

test "render rejects a version for an asset it was not given" {
    try std.testing.expectError(
        error.UnknownAsset,
        render(std.testing.allocator, "{{version:app.js}}", "{}", &.{}),
    );
}

test "the hash follows the asset content" {
    try std.testing.expect(std.hash.Wyhash.hash(0, "a") != std.hash.Wyhash.hash(0, "b"));
    try std.testing.expectEqual(std.hash.Wyhash.hash(0, "same"), std.hash.Wyhash.hash(0, "same"));
}

const test_palette = "palette K #000000\npalette Y #ffff00\n";
const test_blank_row = "." ** icon_size ++ "\n";
const test_icon_rows = "KK" ++ "." ** 12 ++ "YY\n" ++ test_blank_row ** (icon_size - 1);

test "renderIcons merges a run of one colour into a single rect" {
    const source = test_palette ++ "favicon sun\nicon sun\n" ++ test_icon_rows;
    const icons = try renderIcons(std.testing.allocator, source);
    defer icons.deinit(std.testing.allocator);

    try std.testing.expect(std.mem.find(u8, icons.sprite, "<symbol id=\"sun\" viewBox=\"0 0 16 16\"") != null);
    try std.testing.expect(std.mem.find(u8, icons.sprite, "<rect x=\"0\" y=\"0\" width=\"2\" height=\"1\" fill=\"#000000\"/>") != null);
    try std.testing.expect(std.mem.find(u8, icons.sprite, "<rect x=\"14\" y=\"0\" width=\"2\" height=\"1\" fill=\"#ffff00\"/>") != null);
    try std.testing.expect(std.mem.startsWith(u8, icons.favicon, "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 16 16\""));
    try std.testing.expect(std.mem.find(u8, icons.favicon, "width=\"2\"") != null);
}

test "renderIcons ignores comments and blank lines" {
    const source = "# note\n\n" ++ test_palette ++ "\nfavicon sun\n# another\nicon sun\n" ++ test_icon_rows;
    const icons = try renderIcons(std.testing.allocator, source);
    defer icons.deinit(std.testing.allocator);
    try std.testing.expect(icons.sprite.len > 0);
}

test "renderIcons rejects a row of the wrong width" {
    const source = test_palette ++ "favicon sun\nicon sun\nKK\n";
    try std.testing.expectError(error.BadRowWidth, renderIcons(std.testing.allocator, source));
}

test "renderIcons rejects a letter with no palette entry" {
    const source = test_palette ++ "favicon sun\nicon sun\n" ++ "Z" ++ "." ** 15 ++ "\n";
    try std.testing.expectError(error.UnknownPaletteLetter, renderIcons(std.testing.allocator, source));
}

test "renderIcons rejects an icon with too few rows" {
    const source = test_palette ++ "favicon sun\nicon sun\n" ++ test_blank_row;
    try std.testing.expectError(error.IncompleteIcon, renderIcons(std.testing.allocator, source));
}

test "renderIcons rejects a favicon that names no icon" {
    const source = test_palette ++ "favicon moon\nicon sun\n" ++ test_icon_rows;
    try std.testing.expectError(error.UnknownFavicon, renderIcons(std.testing.allocator, source));
}

test "renderIcons rejects a duplicate icon name" {
    const source = test_palette ++ "favicon sun\nicon sun\n" ++ test_icon_rows ++ "icon sun\n" ++ test_icon_rows;
    try std.testing.expectError(error.BadIconName, renderIcons(std.testing.allocator, source));
}

test "renderIcons rejects a malformed palette colour" {
    try std.testing.expectError(
        error.BadPaletteColor,
        renderIcons(std.testing.allocator, "palette K black\nfavicon sun\nicon sun\n" ++ test_icon_rows),
    );
}
