const std = @import("std");

const max_file_bytes = 1024 * 1024;

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 5) return error.InvalidArguments;

    const allocator = init.gpa;
    const cwd = std.Io.Dir.cwd();
    const template = try cwd.readFileAlloc(init.io, args[1], allocator, .limited(max_file_bytes));
    defer allocator.free(template);
    const pl_locale = try cwd.readFileAlloc(init.io, args[2], allocator, .limited(max_file_bytes));
    defer allocator.free(pl_locale);
    const en_locale = try cwd.readFileAlloc(init.io, args[3], allocator, .limited(max_file_bytes));
    defer allocator.free(en_locale);

    const pl_html = try render(allocator, template, pl_locale);
    defer allocator.free(pl_html);
    const en_html = try render(allocator, template, en_locale);
    defer allocator.free(en_html);

    var generated: std.Io.Writer.Allocating = .init(allocator);
    defer generated.deinit();
    try generated.writer.print(
        "// Generated by tools/i18n_gen.zig; do not edit.\n" ++
            "pub const pl_html = \"{f}\";\n" ++
            "pub const en_html = \"{f}\";\n",
        .{ std.zig.fmtString(pl_html), std.zig.fmtString(en_html) },
    );

    try cwd.writeFile(init.io, .{ .sub_path = args[4], .data = generated.written() });
}

fn render(allocator: std.mem.Allocator, template: []const u8, locale_json: []const u8) ![]u8 {
    var parsed = try std.json.parseFromSlice(std.json.Value, allocator, locale_json, .{});
    defer parsed.deinit();

    const translations = switch (parsed.value) {
        .object => |object| object,
        else => return error.LocaleMustBeObject,
    };

    var output: std.ArrayList(u8) = .empty;
    errdefer output.deinit(allocator);

    var position: usize = 0;
    while (std.mem.findPos(u8, template, position, "{{")) |open| {
        try output.appendSlice(allocator, template[position..open]);
        const key_start = open + 2;
        const close_relative = std.mem.find(u8, template[key_start..], "}}") orelse {
            return error.UnclosedPlaceholder;
        };
        const key_end = key_start + close_relative;
        const key = template[key_start..key_end];
        if (key.len == 0) {
            return error.EmptyPlaceholder;
        }

        const value = translations.get(key) orelse return error.MissingTranslation;
        const text = switch (value) {
            .string => |string| string,
            else => return error.TranslationMustBeString,
        };
        try appendHtmlEscaped(&output, allocator, text);
        position = key_end + 2;
    }
    try output.appendSlice(allocator, template[position..]);

    return output.toOwnedSlice(allocator);
}

fn appendHtmlEscaped(output: *std.ArrayList(u8), allocator: std.mem.Allocator, text: []const u8) !void {
    for (text) |byte| switch (byte) {
        '&' => try output.appendSlice(allocator, "&amp;"),
        '<' => try output.appendSlice(allocator, "&lt;"),
        '>' => try output.appendSlice(allocator, "&gt;"),
        '\"' => try output.appendSlice(allocator, "&quot;"),
        '\'' => try output.appendSlice(allocator, "&#39;"),
        else => try output.append(allocator, byte),
    };
}

test "render substitutes translations and escapes HTML" {
    const template = "<p title=\"{{title}}\">{{message}}</p>";
    const locale =
        \\{
        \\  "title": "A & B",
        \\  "message": "Use <tags> safely"
        \\}
    ;

    const rendered = try render(std.testing.allocator, template, locale);
    defer std.testing.allocator.free(rendered);

    try std.testing.expectEqualStrings("<p title=\"A &amp; B\">Use &lt;tags&gt; safely</p>", rendered);
}

test "render rejects a missing translation" {
    try std.testing.expectError(
        error.MissingTranslation,
        render(std.testing.allocator, "{{missing}}", "{}"),
    );
}
